name: Deploy to Azure

on:
  push:
    branches:
      - main  # Trigger the workflow when pushing to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup .NET (if your project is .NET-based)
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0' # Adjust version based on your project

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Step 4: Build the project
      - name: Build the project
        run: dotnet build --no-restore

      # Step 5: Publish the project
      - name: Publish project
        run: dotnet publish --configuration Release --output ./publish --arch x64
      - name: Debug GitHub Environment Variables
        run: env | sort
      #Allow unsecure temporary  
      - name: Allow Unsecure Commands
        run: echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV


      # Step 6: Deploy to Azure
      - name: Set Azure User Agent
        run: echo "AZURE_HTTP_USER_AGENT=GITHUBACTIONS_DeployWebAppToAzure" >> $GITHUB_ENV

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2.0.0  # For Azure Function
        with:
          app-name: testshwetaresource  # Replace with your Azure App Service name
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}  # Set secret in GitHub

      # For Azure App Services (non-Function App):
      # - name: Deploy to Azure Web App
      #   uses: azure/webapps-deploy@v2
      #   with:
      #     app-name: <your-app-name>
      #     publish-profile: ${{ secrets.AZURE_APP_SERVICE_PUBLISH_PROFILE }}
