name: Build and Deploy .NET App to Azure

on:
  push:
    branches:
      - main  # Runs on push to 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use windows-latest if needed

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.405'  # Change to your .NET version

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build the Application
        run: dotnet build --configuration Release --no-restore

      - name: Publish the Application
        run: dotnet publish -c Release -o publish

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: published-app
          path: publish/
          include-hidden-files: true


  deploy:
    runs-on: ubuntu-latest
    needs: build  # Runs after the 'build' job

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: published-app
          path: publish/

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: "testshwetaapp"  # Change to your Azure Web App name
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          package: publish/